### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by cruisek4n** [cruisek4n/furima-33054#10]
# フリマアプリのURL
https://furima-33054.herokuapp.com/

# Basic認証のIDとパスワード
ID:ayakaoppa 
password:04160916

# 出品者用のメールアドレスとパスワード
メールアドレス:item01@yahoo.co.jp
パスワード:item0101
# 購入者用のメールアドレスとパスワード
メールアドレス:purchase01@yahoo.co.jp
パスワード:purchase0101
# 購入用カードの番号・期限・セキュリティコード
カード番号：4242424242424242
cvc: 123
exp_month: 9
exp_year: 25

**Comment by tech-oa** [comment]
cruisek4nさん、ご提出ありがとうございます‼︎大変お待たせいたしました。
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。
また、以下の点は必須機能ではありませんが、ユーザー視点で捉えると不自然だと感じますので、指摘させていただきます。
◯添付した画像のように、ユーザー名の隣にハングル文字と絵文字が表示されています。
この部分だけハングル文字ですとユーザーは不自然に感じるかと思いますので、修正することを推奨します。
![全画面_2021_02_22_16_09](https://user-images.githubusercontent.com/62542016/108674528-c2aa1480-7528-11eb-83f2-9ac37e74fd16.jpg)

追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

**Comment by tech-oa** [comment]
cruisek4nさん、ご提出ありがとうございます‼︎大変お待たせいたしました。
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。
また、以下の点は必須機能ではありませんが、ユーザー視点で捉えると不自然だと感じますので、指摘させていただきます。
◯添付した画像のように、ユーザー名の隣にハングル文字と絵文字が表示されています。
この部分だけハングル文字ですとユーザーは不自然に感じるかと思いますので、修正することを推奨します。
<img width="1043" alt="FurimaUserId" src="https://user-images.githubusercontent.com/62542016/108682201-5d0f5580-7533-11eb-8735-e24741f63a1f.png">

追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
